name: Build APKs Based on Current Content
on:
  workflow_dispatch:

jobs:
  buildAPKs:
    name: build APKs from current content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js & pnpm
        uses: ./.github/actions/setup

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17

      - name: Add upload key secrets for signing APKs
        run: |
          git submodule update --init --recursive
          echo "${{ secrets.RELEASE_CRED }}" >> ./android/gradle.properties

      - name: Build upload keystore `.jks` file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "keystore.jks"
          fileDir: "./android/app"
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Clean generated builds
        run: rm -rf android/app/build/generated/

      - name: Build and sign APKs with Gradle
        run: cd android && chmod +x gradlew && ./gradlew assembleRelease

      - name: Upload APKs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputAPKs
          path: android/app/build/outputs/apk/release/*.apk

      - name: Zip deobfuscation files
        run: |
          zip -j deobfuscate.zip ./android/app/build/outputs/mapping/release/mapping.txt \
                              ./android/app/build/outputs/native-debug-symbols/release/native-debug-symbols.zip

      - name: Upload deobfuscation files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deobfuscate
          path: deobfuscate.zip
